POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST client is pretty good",
    "important": false
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "User id of the note creator is at the start sent along the request",
    "important": true,
    "userId": "6171a1adfaa597c56105968d"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "The existing code and tests need to be changed when user is added to system",
    "important": true,
    "userId": "6171a1adfaa597c56105968d"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer hbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MTcxYTFhZGZhYTU5N2M1NjEwNTk2OGQiLCJpYXQiOjE2MzUyMDg0NTZ9.gk9YaTOqhjmYBB4Yw70TB3dcjn-r_VThI-L2qhLLu70

{
    "content": "Single Page Apps use token authentication",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/6151ca9a3d9884f127097f4a
Content-Type: application/json
